
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'HASHTAG NEWLINE OP START VARfexpression : START expression HASHTAG NEWLINEexpression : expression OP VAR\n\t\t\t\t  | VAR'
    
_lr_action_items = {'START':([0,],[2,]),'$end':([1,7,],[0,-1,]),'VAR':([2,6,],[4,8,]),'HASHTAG':([3,4,8,],[5,-3,-2,]),'OP':([3,4,8,],[6,-3,-2,]),'NEWLINE':([5,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'fexpression':([0,],[1,]),'expression':([2,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> fexpression","S'",1,None,None,None),
  ('fexpression -> START expression HASHTAG NEWLINE','fexpression',4,'p_sful','untitled.py',27),
  ('expression -> expression OP VAR','expression',3,'p_expr','untitled.py',32),
  ('expression -> VAR','expression',1,'p_expr','untitled.py',33),
]
